insert into o_SPORT_DISCIPLINES (D_ID,NAME) values (301,'Table Tennis');
insert into o_SPORT_DISCIPLINES (D_ID,NAME) values (302,'Football');
insert into o_SPORT_DISCIPLINES (D_ID,NAME) values (303,'Synchronised Swimming');
insert into o_SPORT_DISCIPLINES (D_ID,NAME) values (304,'Athletics');
insert into o_SPORT_DISCIPLINES (D_ID,NAME) values (305,'Equestrian');
insert into o_SPORT_DISCIPLINES (D_ID,NAME) values (306,'Taekwondo');
insert into o_SPORT_DISCIPLINES (D_ID,NAME) values (307,'Baseball');
insert into o_SPORT_DISCIPLINES (D_ID,NAME) values (308,'Shooting');
insert into o_SPORT_DISCIPLINES (D_ID,NAME) values (309,'Tennis');
insert into o_SPORT_DISCIPLINES (D_ID,NAME) values (310,'Wrestling');
insert into o_SPORT_DISCIPLINES (D_ID,NAME) values (311,'Diving');
insert into o_SPORT_DISCIPLINES (D_ID,NAME) values (312,'Badminton');
insert into o_SPORT_DISCIPLINES (D_ID,NAME) values (313,'Judo');
insert into o_SPORT_DISCIPLINES (D_ID,NAME) values (314,'Road Cycling');
insert into o_SPORT_DISCIPLINES (D_ID,NAME) values (315,'Gymnastics');
insert into o_SPORT_DISCIPLINES (D_ID,NAME) values (316,'Rowing');
insert into o_SPORT_DISCIPLINES (D_ID,NAME) values (317,'Boxing');
insert into o_SPORT_DISCIPLINES (D_ID,NAME) values (318,'Tranpoline');
insert into o_SPORT_DISCIPLINES (D_ID,NAME) values (319,'Field Hockey');
insert into o_SPORT_DISCIPLINES (D_ID,NAME) values (320,'Modern Pentathlon');
insert into o_SPORT_DISCIPLINES (D_ID,NAME) values (321,'Triathlon');                 insert into o_SPORT_DISCIPLINES (D_ID,NAME) values (322,'Montain Cycling');           insert into o_SPORT_DISCIPLINES (D_ID,NAME) values (323,'Track Cycling');             
insert into o_SPORT_DISCIPLINES (D_ID,NAME) values (324,'Swimming');                  
insert into o_SPORT_DISCIPLINES (D_ID,NAME) values (325,'Archery');                   
insert into o_SPORT_DISCIPLINES (D_ID,NAME) values (326,'Rhythmic Gymnastics'); 
insert into o_SPORT_DISCIPLINES (D_ID,NAME) values (327,'Sailing');             
insert into o_SPORT_DISCIPLINES (D_ID,NAME) values (328,'Canoe/kayak');
insert into o_SPORT_DISCIPLINES (D_ID,NAME) values (329,'Volleyball');
insert into o_SPORT_DISCIPLINES (D_ID,NAME) values (330,'Fencing'); 
insert into o_SPORT_DISCIPLINES (D_ID,NAME) values (331,'Canoe/Kayak (slalom'); 
insert into o_SPORT_DISCIPLINES (D_ID,NAME) values (332,'Softball');
insert into o_SPORT_DISCIPLINES (D_ID,NAME) values (333,'Water Polo');
insert into o_SPORT_DISCIPLINES (D_ID,NAME) values (334,'Handball');
insert into o_SPORT_DISCIPLINES (D_ID,NAME) values (335,'Beach Volleyball');
insert into o_SPORT_DISCIPLINES (D_ID,NAME) values (336,'Basketball');
insert into o_SPORT_DISCIPLINES (D_ID,NAME) values (337,'Weightlifting');     
commit;
